apiVersion: 1
datasources:
  - name: Tempo
    type: tempo
    uid: tempo
    access: proxy
    url: http://tempo:3200
    jsonData:
      httpMethod: GET
      serviceMap:
        datasourceUid: 'prometheus'
      nodeGraph:
        enabled: true
      lokiSearch:
        datasourceUid: 'loki'
      tracesToLogsV2:
        datasourceUid: 'loki'
        tags: ['app']
      tracesToMetrics:
        datasourceUid: 'prometheus'
        tags: [{ key: 'service.name', value: 'service' }]
